version: "2"
services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    # depends_on:
    #   - serviceName
    ports:
      - 8080:8080
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80
