# Generated by Django 4.2.4 on 2023-08-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsersApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="check_status",
        ),
        migrations.AddField(
            model_name="users",
            name="user_check",
            field=models.CharField(blank=True, db_column="check", max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="birth",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_num",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="updated_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
