# Generated by Django 4.2.4 on 2023-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsersApp", "0002_remove_users_check_status_users_user_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
