spring:

#  datasource:
#    url: jdbc:postgresql://${CLOUD_AWS_DB_HOST}:5432/${CLOUD_AWS_DB_DATABASE_NAME}
#    username: ${CLOUD_AWS_DB_USERNAME}
#    password: ${CLOUD_AWS_DB_PASSWORD}
#    driverClassName: org.postgresql.Driver

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: techeer_market
    password: techeer1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
