spring:
  datasource:
    url: jdbc:postgresql://${CLOUD_AWS_DB_HOST}:5432/${CLOUD_AWS_DB_DATABASE_NAME}
    username: ${CLOUD_AWS_DB_USERNAME}
    password: ${CLOUD_AWS_DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  redis:
    host: ${REDIS_AWS_HOST}

springdoc:
  version: v1
  packages-to-scan: com.example.backend # swagger 적용 위해 스캔할 패키지
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html # swagger-ui 연결할 주소
    tags-sorter: alpha # alpha: 알파벳 순 정렬, method: HTTP method 순 정렬
    operations-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true